# basic configuration
server:
  port: 8080
  servlet:
    context-path: /testbox/

# database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testbox?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: HTML
#  #这个是关键，放开springboot对静态资源的拦截
#  mvc:
#    static-path-pattern: /static/**


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml
  type-aliases-package: com.bjtu.testbox.entity

#showSql
logging:
  level:
    com:
      ztz:
        mapper : info