# basic configuration
server:
  port: 8080
  servlet:
    context-path: /testbox/

# database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testbox?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 阿里巴巴数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml
  type-aliases-package: com.bjtu.testbox.entity

#showSql
logging:
  level:
    com:
      ztz:
        mapper : info